name: conserta_ja
description: A new Flutter project
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  mask_text_input_formatter: ^2.5.0
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/consertaja.png
    - assets/email.png
    - assets/google.png
    - assets/facebook.png
    - assets/telefone.png
    - assets/header.jpg
    - assets/documento.png
    - assets/perfil.png
    - assets/consertogeral.png
    - assets/eletricista.png
    - assets/encanador.png
    - assets/pedreiro.png
    - assets/pintor.png
    - assets/cupom.png